### ISSUE TITLE
Images are missing in the grid boxes when restoring a course

### ISSUE THREAD

**Issue by neeesn** [gjb2048/moodle-format_grid#172] opened 2023-01-05 09:32 UTC
When we copy courses, the images in tiles are missing.
The images are in the "Master" but not in the new course. 

The same issue if we import into an existing course, the images in the tiles are missing. 

We are currently on Moodle 4.0.4+ (Build: 20221018)

**Comment by gjb2048** [comment] 2023-01-05 09:34
What Grid version please.

**Comment by gjb2048** [comment] 2023-01-06 12:35
Copy course works.  Importing won't as that is intentional as source images could overwrite destination images.

**Comment by JRinggren** [comment] 2023-01-11 15:07
We are experiencing that tiles images are only copied correctly if they are present in both image section and short description. Is that expected behavior?

**Comment by gjb2048** [comment] 2023-01-11 15:44
No.  And my test only had the images in the image section and not the section summary, thus cannot replicate.

**Comment by gjb2048** [comment] 2023-01-24 18:17
Possibly related to comments by Michael Woods on https://moodle.org/plugins/format_grid.

**Comment by gjb2048** [comment] 2023-03-04 17:33
No reply in ages, closing.

**Comment by JRinggren** [comment] 2023-03-13 13:27
Hi again,
Sorry to open this up again.
It seems we have a site experiencing the same issues as Michael Woods like you suggested.
The scenario is that importing or restoring (while deleting existing content) into an existing course doesn't contain section images. You report that you will get around to thinking of a solution at some point. Do you have any time frame for this, that we can report to our siteowners?

**Comment by gjb2048** [comment] 2023-03-13 13:33
@JRinggren No time frame, I tend to look at issues for non-clients when I get a moment or need the challenge of solving the problem.

**Comment by JRinggren** [comment] 2023-03-13 13:36
Hi again!
Okay. Thanks for the reply!

**Comment by aspark21** [comment] 2023-08-09 15:03
Hi Gareth,

happy to fund this

Al

**Comment by aspark21** [comment] 2023-08-09 15:05
@hovez701 can provide more details if you still have issues replicating

**Comment by gjb2048** [comment] 2023-08-09 15:20
@aspark21 Thanks, but need to be convinced that the correct issue is being solved as there seems to be two different scenarios going on here.  The one that I could potentially address is when the user requests that the target course has its contents deleted.  However that won't affect the this issue as that relates to course duplication, which I cannot replicate.  G.

**Comment by gjb2048** [comment] 2023-08-09 15:22
Info:

![Screenshot 2023-08-09 162130](https://github.com/gjb2048/moodle-format_grid/assets/1058419/23d40b16-9da4-4065-baa1-d1404fd251bc)

**Comment by hovez701** [comment] 2023-08-10 10:42
Hi @gjb2048 , we are getting this issue from our course rollover plugin, which creates a new blank course first and then restores the backup into that new course. We believe this matches your scenario 1.

**Comment by gjb2048** [comment] 2023-08-10 10:48
@hovez701 Ok, so how can I programmatically detect that the target course is blank and that the contents require deleting?  Do you tell the restore process what type of restore it is?  Or rather, why don't you just instigate the duplication mechanism instead?

**Comment by aydevworks** [comment] 2023-08-10 10:52
> @hovez701 Ok, so how can I programmatically detect that the target course is blank and that the contents require deleting? Do you tell the restore process what type of restore it is? Or rather, why don't you just instigate the duplication mechanism instead?

Hi @gjb2048,

It's always a blank course and restore using the moodle restore_controller.
`$restore = new restore_controller($backup['id'], $course->id, backup::INTERACTIVE_NO, backup::MODE_GENERAL,
            $USER->id, backup::TARGET_CURRENT_DELETING);`

**Comment by gjb2048** [comment] 2023-08-10 10:55
@aydevworks Thanks, I'll do some thinking.  Where I can I get the 'course rollover plugin' from to test with please?  Instructions etc. too.

**Comment by aydevworks** [comment] 2023-08-10 11:02
@gjb2048 Thanks, but could you please try to resolve this scenario first?
_"The one that I could potentially address is when the user requests that the target course has its contents deleted."_

Then we can test it from our side as the course rollover plugin required a few other plugins, a bit tricky to setup too. 😄

**Comment by gjb2048** [comment] 2023-08-10 11:15
@aydevworks Ok.

**Comment by aydevworks** [comment] 2023-08-10 11:17
@gjb2048 Thank you! 🙏

**Comment by gjb2048** [comment] 2023-08-10 12:41
@aydevworks - Update with https://github.com/gjb2048/moodle-format_grid/commit/563f54aa31783092d9422c21cbca4260906378b0 - and using xDebug.  Ok, can't get this to work as despite 'define_section_plugin_structure()' being called (as it is when adding a new course) that triggers the calling of 'process_gridsection()', then when merging or deleting into an existing course, then that method is not called.  Even if you set:

![Screenshot 2023-08-10 131658](https://github.com/gjb2048/moodle-format_grid/assets/1058419/66fb5c7c-6105-4c15-8575-d1437f446ba3)

then only 'after_restore_course()' is called and thus no section data with the images is there to process.

I'm really not sure what is going on with the core API here!  Do you know of any experts?

G

**Comment by gjb2048** [comment] 2023-08-10 16:36
Dear @aydevworks

After extensive debugging of the parent method 'process()' in 'backup/util/plan/restore_structure_step.class.php' when deleting into an existing course, it was actually calling 'process_gridsection()', however it appears that the red herring is:

`$restore = new restore_controller($backup['id'], $course->id, backup::INTERACTIVE_NO, backup::MODE_GENERAL, $USER->id, backup::TARGET_CURRENT_DELETING);`

which should be:

`$restore = new restore_controller($backup['id'], $course->id, backup::INTERACTIVE_NO, backup::MODE_GENERAL, $USER->id, backup::TARGET_EXISTING_DELETING);`

G

**Comment by gjb2048** [comment] 2023-08-10 16:39
P.S.

Actually:

![Screenshot 2023-08-10 173905](https://github.com/gjb2048/moodle-format_grid/assets/1058419/7806e0b3-77d4-4607-a50d-01214cb69947)


Probably both!  But will await your results.

**Comment by aydevworks** [comment] 2023-08-10 21:53
Hi @gjb2048 , thank you so much for your updates.

I have tested on my local and one of our preview server. It didn't matter if I pass `backup::TARGET_CURRENT_DELETING`  or  `backup::TARGET_EXISTING_DELETING` to the `restore_controller`. The `process_gridsection` had been called for both of them.

I have updated your solution a bit to include `backup::TARGET_CURRENT_DELETING` and remove the code for deleting the images in method `process_gridsection`.

With this update, https://github.com/aydevworks/moodle-format_grid/commit/d96ee0d03f59c573aaa0ae883fda0ed9d47c22a3, the test results were all good.

Otherwise, only the last image was written into the `format_grid_image` table.
![image](https://github.com/gjb2048/moodle-format_grid/assets/47617421/a01d3045-1adc-4446-880c-d9a85473dc06)

The old images for the existing course were deleted when the `course_content_deleted` is observed.
https://github.com/aydevworks/moodle-format_grid/blob/master/classes/observer.php#L45

Therefore, I guess we have found the solution 😄

**Comment by gjb2048** [comment] 2023-08-11 10:46
@aydevworks Thanks, not spotted that!  Just a logic issue with the image removal.  But I don't want to rely on a the event / observer mechanism in a multi-processor / core environment or go down a locking solution.  Also there's more to look at, as I think that when merging that the files are still restored and available via the Files API / files table and yet the format won't know about this.  Is merging also something you're interested in being fixed? i.e. if an image does not exist in the destination but does in the source, then its used?

**Comment by gjb2048** [comment] 2023-08-11 15:08
P.S. Had to rebase as fixed a bug outside of this issue.

**Comment by gjb2048** [comment] 2023-08-11 15:15
P.P.S. Nope - "And on a merge when they are not, then they don't show in the files table, even though the restore mechanism -> 'process()' in 'backup/util/plan/restore_structure_step.class.php' indicates a 'files' restore process for the images that are in the backup file... unless, and I've yet to check, these were the old 'course/section' component/filearea files that are in my test courses before these recent changes and I've not breakpointed this in 'process' yet for a backup created from a new Grid course that doesn't have them." - tested and the files are being parsed - not sure what's going on.

**Comment by gjb2048** [comment] 2023-08-15 15:53
@hovez701 Any news on this from your end please?

**Comment by gjb2048** [comment] 2023-08-15 18:11
@aspark21 Thanks.  I thought you were on holiday?

**Comment by aspark21** [comment] 2023-08-15 18:55
back for one day only and then off again 😄

**Comment by gjb2048** [comment] 2023-08-16 21:45
Released in https://moodle.org/mod/forum/discuss.php?d=449513 - with merge (when no image in destination and image in source, then source image gets used) and delete.

**Closed by gjb2048** 2023-08-16 21:45 UTC
Labels: Bug

**Comment by phette23** [comment] 2023-08-16 21:47
Is there any chance for a backport to 4.0? We are also affected by this in a similar context (using [local_course_template](https://moodle.org/plugins/local_course_template) plugin) and are on 4.0.

**Comment by gjb2048** [comment] 2023-08-17 10:52
@phette23 Between one to two hours at my current rate of 44 GBP per hour as I'll need to backport all of this:

![Screenshot 2023-08-17 114732](https://github.com/gjb2048/moodle-format_grid/assets/1058419/39b11ccd-2a09-46d2-a58e-409c0d2e0e49)

too, in order to keep things in sync + a Moodle dot org release.  Please use the eMail address at the top of Support.md - note that I'm in the UK and I see you're in the US, so please let me know of any issues pertaining to your use of international contractors.
