### ISSUE TITLE
[3.3] "Cannot create local file Pool file" for the "grid" view of courses in the LMS

### ISSUE THREAD

**Issue by Novocastrian** [gjb2048/moodle-format_grid#88] opened 2019-03-18 01:05 UTC
Hi!

One of our Moodle 3.3 LMSs recently encountered an issue with the "grid" view for courses. As you can see in the attached screenshot (affected course grid view.png), the grid only shows the first section (section=0), then displays the error for the remaining sections. The remaining sections are navigatable via URL manipulation (www.MoodlLMSURLHere.com/course/view.php?id=1234&section=5, for example), and they resolve valid pages, ruling out corruption on the sections. Changing the view settings within the course settings (unit, onetopic, etc.) displays the links to those sessions as they should for those settings.

I backed up this affected course and restored it to the same LMS, with some success. The grid view displayed the sections correctly for less than an hour before showing the same message. However, performing additional restores of the course within the same LMS instantly replicates this issue with the grid view.

The screenshot "Staging Site AS-IS Grid View.png" is a screenshot of the course i restored today to our Staging environment for the LMS (same infrastructure). This is how it should appear in the affected moodle site. The grid settings (/admin/settings.php?section=formatsettinggrid) are exactly the same between the affected LMS and the Staging environment LMS.

This occurs to each course within the affected LMS using the "Grid" format. What could cause this issue with the grid format? I've discussed this with the owner of the website and the server administrators, and they believe nothing has changed to the affected LMS this year. According to the customer that lodged this issue, this issue was not present at the start of last week. Any ideas? 

Affected Course Grid View: https://imgur.com/4QQKrmc
Staging Site AS-IS Grid View: https://imgur.com/eJhkGr4

**Comment by gjb2048** [comment] 2019-03-18 11:33
Have you clicked on 'More information about this error'?  If so, what does it say?

**Comment by gjb2048** [comment] 2019-03-18 11:34
Images for reference:

![4QQKrmc](https://user-images.githubusercontent.com/1058419/54527413-bf3ba500-4971-11e9-84b9-b87bb4be3b9d.png)

![eJhkGr4](https://user-images.githubusercontent.com/1058419/54527427-cc589400-4971-11e9-8728-040ce999cb25.png)

**Comment by gjb2048** [comment] 2019-03-18 11:36
Have you turned on developer debugging?  What does it say in the stack trace?

**Comment by gjb2048** [comment] 2019-03-18 11:39
Looking at the usage of the 'storedfilecannotcreatefile' this is all related to permissions with the file system, thus pertaining to the ability for the format to create the displayed image or something else to do with the course content.  Thus a server issue with permissions etc. or iffy course content.

**Comment by gjb2048** [comment] 2019-03-18 11:40
Stack trace really important now.

**Comment by Novocastrian** [comment] 2019-03-19 23:27
Hi @gjb2048, 

Please see the below stack trace that shows on page load. 
`Debug info:
Error code: storedfilecannotcreatefile
Stack trace:

    line 500 of \lib\filestorage\file_system_filedir.php: file_exception thrown
    line 1776 of \lib\filestorage\file_storage.php: call to file_system_filedir->add_file_from_string()
    line 1435 of \lib\filestorage\file_storage.php: call to file_storage->add_string_to_pool()
    line 2059 of \course\format\grid\lib.php: call to file_storage->create_file_from_string()
    line 733 of \course\format\grid\renderer.php: call to format_grid->setup_displayed_image()
    line 387 of \course\format\grid\renderer.php: call to format_grid_renderer->make_block_icon_topics()
    line 241 of \course\format\grid\format.php: call to format_grid_renderer->print_multiple_section_page()
    line 280 of \course\view.php: call to require()`

**Comment by gjb2048** [comment] 2019-03-20 11:24
Ok, given the stack trace.  There appears to be an issue with either the storage capability or permissions of your server.  Unless there is an infinite loop going on - a hunch - so are there any errors in the PHP log file?

**Comment by gjb2048** [comment] 2019-03-20 11:25
Also, what are the contents of the 'format_grid_icon' table please?

**Comment by Novocastrian** [comment] 2019-03-22 01:02
Hi @gjb2048,

There are no errors relating to the course (searched for the courseID and course name w/ no results) within the _php-errors.log_ file. This file has been recording site errors since Dec 2018, so the LMS is reporting the errors to file correctly.  

The _format_grid_icon_ table shows the following results for this course:

id | image | sectionid | courseid | displayedimageindex
-- | -- | -- | -- | --
2378 | Learning.jpg | 16706 | 1520 | 1
2379 | Mixed students.jpg | 16707 | 1520 | 0
2380 | Resources.jpg | 16708 | 1520 | 0
2381 | Support.jpg | 16709 | 1520 | 0
2382 | Puzzle.jpg | 16710 | 1520 | 0
2383 | Start Here image_2.png | 16711 | 1520 | 0
2384 | Handshake.jpg | 16712 | 1520 | 0
2385 | Books.jpg | 16713 | 1520 | 0

**Comment by gjb2048** [comment] 2019-03-22 13:52
Ok, information is useful with 'displayedimageindex', still looks like a file storage issue or the conversion process to displayed image is failing due to the size of the image.  How big is 'Mixed students.jpg' etc?

**Comment by gjb2048** [comment] 2019-04-02 15:50
Is this still an issue please?

**Comment by Novocastrian** [comment] 2019-04-03 23:17
Hi @gjb2048, 

My apologies for my non-response. The images are web-optimised, so they are no larger than 1MB (some are huge images dimension-wise).

**Comment by gjb2048** [comment] 2019-04-04 08:45
The HTML does not do the rescaling, the Grid format does that in PHP - this whole issue.  A 1MB image!  For a web page!  That's big!

**Comment by gjb2048** [comment] 2019-04-12 21:05
Ok, on M3.6 V3.6.0.5 version, just tried a 6.57MB jpg file and cannot replicate!  Therefore I can only assume now that this is an issue with your local server / configuration of such.

**Comment by Novocastrian** [comment] 2019-04-15 23:22
Hi @gjb2048,

My apologies for my belated response. I recognise that it is a huge file with respect to web design principles, but the teachers created this course and took the images from one of the copyright-free websites, so I have to work with what I have in this case :/

Ok, let's go down the file permissions troubleshooting line. Do you know what the minimum permission levels this needs on the server? This is on a Linux VM (14.04, I think).

**Comment by gjb2048** [comment] 2019-04-16 14:46
Ok,

Given that I cannot replicate with a 6.57MB jpg file, then clearly there is nothing for me to correct in the actual Grid code or its use of the core API's or report as an issue on Moodle.org with the core API's.  Therefore the issue is specific to your site and outside of the scope of free support that I provide.

I'd be happy to discuss terms of business if you'd like to continue with this.  Or if it later transpires that it is an issue with my code then I'll look at it again.

I don't know the minimum permission levels as every development server, both Windows and Linux (Ubuntu be it 14.x, 16.x, 18.x etc.) has not had the issue straight out of the box.

Kind regards,

Gareth

**Comment by gjb2048** [comment] 2019-05-10 16:39
Ok, as there has been no reply, I'm closing as 'Cannot reproduce'.

**Comment by gjb2048** [comment] 2019-11-16 13:08
Closed as no reply.

**Closed** 2019-11-16 13:08 UTC
Labels: Cannot reproduce

**Comment by watcanz** [comment] 2020-02-11 20:55
I am getting this error.  Clearing cache did not help, but switching out of Grid and then back into removed the message and allowed the remainder of the images to load.  However, the images will not scale, and making any changes in the Course Settings and saving result in the same Cannot create local pool error message.

This addon uses PHP to resize images?  Could this be a permission issue?  If so, what permissions are incorrect?

**Comment by gjb2048** [comment] 2020-02-11 22:17
@watcanz It uses the GD library that Moodle does and the file API.  I have never ever got to to bottom of why this is happening.

What version of the format and Moodle are you running?  Has the disk ran out of space?

**Comment by watcanz** [comment] 2020-02-11 22:26
So strange.

Moodle 3.6.8+  PHP7.0 on a WHM/cPanel server with plenty of disk space.  Grid is 3.6.1.0
2018121907.  

I actually changed the specific account to have unlimited drive space as well.  Server uses cPanel's MultiPHP so multiple versions are running, but they all have GD installed.

So here is another strange thing.  All of the images were 128X128px before I upgraded today.  After the upgrade, in this one course, we got that error, I got it to clear, but the images were now 128X85px.  I thought they were initially and did not scale, but actually, they seem to have been reduced.  As we replace with new images, the error no longer appears when saving Course Settings.

**Comment by gjb2048** [comment] 2020-02-11 22:58
Odd.  What was the image ratio setting please?

**Comment by gjb2048** [comment] 2020-02-11 23:01
Ok, so 128 x 85 can be generated by a 3:2 ratio which I think is the default.

**Comment by watcanz** [comment] 2020-02-11 23:37
Before the upgrade it was 3:3.  Then the error.  Then I put the course in Topics, then back to Grid which removed the error.  When I did that, it went back to 3:2.  I switched it to 3:3, purged caches, and they remained small.

**Comment by gjb2048** [comment] 2020-02-11 23:40
So are they now 128 by 85 still or 128 by 128? Or something else?

**Comment by gjb2048** [comment] 2020-02-11 23:41
What versions did you upgrade from please?

**Comment by watcanz** [comment] 2020-02-12 00:30
I upgraded the site from 3.1.x to 3.6.x.  I am not sure of the exact version of the Grid.

Images remain 128x85, so we are pulling the 128x128 versions off of a demo site and replacing them.

**Comment by gjb2048** [comment] 2020-02-12 00:39
Oh, ok, I can no longer run 3.1.x so not in a position to replicate.  Have you just tried changing the ratio to something else in the settings and see if that regenerates the images?

**Comment by watcanz** [comment] 2020-02-12 11:56
I cannot do that at this point as they have it back in production.  I will report anything new that might happen.

Thanks for thinking about this.

Jeff

**Comment by gjb2048** [comment] 2020-02-12 15:59
No worries Jeff, if one day I can replicate this then I might have a chance of understanding why.

**Comment by watcanz** [comment] 2020-02-12 16:20
Separate question:  Is there a setting to turn off the tooltip of the grid section title?

**Comment by gjb2048** [comment] 2020-02-12 16:41
Yes -> "Show section title summary on hover option"

**Comment by watcanz** [comment] 2020-02-12 16:46
Thank you, sir.

Jeff
