### ISSUE TITLE
Error when running on Moodle 3.1

### ISSUE THREAD

**Issue by richardsonsamuel** [gjb2048/moodle-format_grid#29] opened 2016-05-12 03:51 UTC
I am using the single section page view.

This error displays on above the grid:
`
String does not exist. Please check your string definition for newactivityname/moodle
line 9669 of /lib/moodlelib.php: call to debugging()
line 58 of /course/classes/output/course_module_name.php: call to lang_string->__construct()
line 712 of /course/renderer.php: call to core_course\output\course_module_name->__construct()
line 973 of /course/renderer.php: call to core_course_renderer->course_section_cm_name()
line 909 of /course/renderer.php: call to core_course_renderer->course_section_cm()
line 1074 of /course/renderer.php: call to core_course_renderer->course_section_cm_list_item()
line 299 of /course/format/grid/renderer.php: call to core_course_renderer->course_section_cm_list()
line 115 of /course/format/grid/renderer.php: call to format_grid_renderer->make_block_topic0()
line 151 of /course/format/grid/format.php: call to format_grid_renderer->print_multiple_section_page()
line 280 of /course/view.php: call to require()
`

This error displays when underneath section0 on a single section page:

`
String does not exist. Please check your string definition for newactivityname/moodle
line 9669 of /lib/moodlelib.php: call to debugging()
line 58 of /course/classes/output/course_module_name.php: call to lang_string->__construct()
line 712 of /course/renderer.php: call to core_course\output\course_module_name->__construct()
line 973 of /course/renderer.php: call to core_course_renderer->course_section_cm_name()
line 909 of /course/renderer.php: call to core_course_renderer->course_section_cm()
line 1074 of /course/renderer.php: call to core_course_renderer->course_section_cm_list_item()
line 779 of /course/format/renderer.php: call to core_course_renderer->course_section_cm_list()
line 149 of /course/format/grid/format.php: call to format_section_renderer_base->print_single_section_page()
line 280 of /course/view.php: call to require()
`

This error displays underneath the section title and section summary on the single section page. It is above the content of the selected section:

`
String does not exist. Please check your string definition for newactivityname/moodle
line 9669 of /lib/moodlelib.php: call to debugging()
line 58 of /course/classes/output/course_module_name.php: call to lang_string->__construct()
line 712 of /course/renderer.php: call to core_course\output\course_module_name->__construct()
line 973 of /course/renderer.php: call to core_course_renderer->course_section_cm_name()
line 909 of /course/renderer.php: call to core_course_renderer->course_section_cm()
line 1074 of /course/renderer.php: call to core_course_renderer->course_section_cm_list_item()
line 816 of /course/format/renderer.php: call to core_course_renderer->course_section_cm_list()
line 149 of /course/format/grid/format.php: call to format_section_renderer_base->print_single_section_page()
line 280 of /course/view.php: call to require()
String does not exist. Please check your string definition for newactivityname/moodle
line 9669 of /lib/moodlelib.php: call to debugging()
line 58 of /course/classes/output/course_module_name.php: call to lang_string->__construct()
line 712 of /course/renderer.php: call to core_course\output\course_module_name->__construct()
line 973 of /course/renderer.php: call to core_course_renderer->course_section_cm_name()
line 909 of /course/renderer.php: call to core_course_renderer->course_section_cm()
line 1074 of /course/renderer.php: call to core_course_renderer->course_section_cm_list_item()
line 816 of /course/format/renderer.php: call to core_course_renderer->course_section_cm_list()
line 149 of /course/format/grid/format.php: call to format_section_renderer_base->print_single_section_page()
line 280 of /course/view.php: call to require()
`

Screenshots attached

<img width="908" alt="screen shot 2016-05-12 at 1 50 30 pm" src="https://cloud.githubusercontent.com/assets/17615012/15203585/83cea574-1848-11e6-9e26-601c46d23416.png">

**Comment by richardsonsamuel** [comment] 2016-05-12 04:27
Ive narrowed the issue for the Grid Page not the single section page down to 

Line 299          echo $this->courserenderer->course_section_cm_list($course, $thissection, 0);

If you remove this line the activities in the section 0 do not display so this line needs to be updated not sure what to though?

Still unsure of whats causing the issue on the single section page view. Will further investigate

**Comment by gjb2048** [comment] 2016-05-12 06:43
Dear Sam,

Given the stack trace the fault is with your installation, not the format.  You've probably updated and not done a purge all caches or the language files are broken.

Kind regards,

Gareth

**Comment by gjb2048** [comment] 2016-05-12 06:45
Or there does need to be a new course format specific definition.  I'll work this out when I make the M3.1 version of the format.

**Comment by richardsonsamuel** [comment] 2016-05-12 06:49
I think the old definition is the issue then because the same errors essentially are on the grid page and single section page. 

Do you have a projected release date for the M3.1 version or what is the progress as my system is currently unreleased hence I would be more than happy to test a beta version of the format if you need. My system will be released later in the year I am just developing it on 3.1 because that is due to be released soon.

Sam

**Comment by gjb2048** [comment] 2016-05-12 06:52
Thanks Sam, no date yet but likely to be June / July.

**Comment by richardsonsamuel** [comment] 2016-05-12 06:54
Yep thats perfect. When you are developing the next version will it be pushed to a new branch in git or are you working on it offline then publishing it upon completion? 

I know some others do that with there Moodle plugins so I'd though to ask.

**Comment by gjb2048** [comment] 2016-05-12 06:55
Current master will become MOODLE_30 then be for M3.1.

**Comment by gjb2048** [comment] 2016-08-17 17:19
Is this still an issue?

**Comment by gjb2048** [comment] 2016-11-15 11:59
Cannot reproduce, closing.

**Closed by gjb2048** 2016-11-15 11:59 UTC
Labels: Cannot reproduce
