### ISSUE TITLE
Toolbar Overlay

### ISSUE THREAD

**Issue by caiado** [gjb2048/moodle-format_grid#37] opened 2016-11-09 12:19 UTC
Hi,

I'm using:

(1) Pionner Theme (https://moodle.org/plugins/theme_pioneer, latest version)
(2) Grid Format (https://moodle.org/plugins/format_grid, version 3.0.1.1)

It seems that when I click into a section the page behind the pop-up window jumps to the top of the page.

When using the Pioneer theme some overlay happens (see image).

Is there a way not to jump to the top of the page when clicking on a section?

Ricardo

![screenshot from 2016-11-09 10-10-10](https://cloud.githubusercontent.com/assets/533328/20138125/bd3e0588-a665-11e6-994f-f5a7ced637e0.png)

**Comment by gjb2048** [comment] 2016-11-09 12:56
The Grid format is implemented correctly for the core themes.  I have made changes to my contributed themes that also had a similar issue.  This is an issue with the Pioneer theme.

**Comment by caiado** [comment] 2016-11-09 13:05
I'm afraid it is not related to the theme. I changed to the "Clear" theme and the behavior is the same: it jumps to the top of the page after I clink on the section.

**Comment by gjb2048** [comment] 2016-11-09 13:08
There is no such theme as the 'Clear' theme.  Please provide evidence.

**Comment by gjb2048** [comment] 2016-11-09 13:10
Also the section area is designed to be underneath the navigation bar.  This is true in the core themes and my contributed ones.  Therefore the Pioneer theme needs to cope with the Grid format and not vice versa.

**Comment by caiado** [comment] 2016-11-09 13:11
Sorry... it is "Clean" theme...

Clicked on the last section and the page jumped to the top.


![screenshot from 2016-11-09 11-10-19](https://cloud.githubusercontent.com/assets/533328/20139415/240fb03e-a66d-11e6-9f47-f02902a2a3ec.png)

**Comment by gjb2048** [comment] 2016-11-09 13:12
That's how it's meant to work, with the shade box being a certain distance from the navbar at the top.

**Comment by gjb2048** [comment] 2016-11-09 13:15
Also the title of the issue is 'Toolbar overlay' not 'Jumps to top when showing Shadebox' which would be a separate issue to be argued.

**Comment by caiado** [comment] 2016-11-09 13:17
"Jumps to top when showing Shadebox"

Is there a way not to jump to the top when showing Shadebox. That would solve it.

**Comment by gjb2048** [comment] 2016-11-09 13:20
Probably.  But that would be an enhancement.  If you figure it out I'll consider integrating the solution.

**Comment by caiado** [comment] 2016-11-09 13:23
ok, thanks...

**Comment by gjb2048** [comment] 2017-02-03 12:45
Is the toolbar overlay still an issue?

**Comment by gjb2048** [comment] 2017-03-22 13:44
No reply after over a month, closing.

**Closed by gjb2048** 2017-03-22 13:44 UTC
Labels: Pending replication
