### ISSUE TITLE
4.0.0.2 database upgrade errors

### ISSUE THREAD

**Issue by abkoch** [gjb2048/moodle-format_grid#166] opened 2022-09-05 17:58 UTC
Hello,

on several Moodles (4.0.3, Build  20220822) an update of format_grid from 3.9.1.5 (202007) to 4.0.0.2 (2022072201) fails with database errors similar to the following (XXXX replaced due to privacy issues):

```
!! Duplicate entry 'XXXX' for key 'mdl_formgridimag_sec_uix'
INSERT INTO mdl_format_grid_image (sectionid,courseid,image,displayedimagestate) VALUES(?,?,?,?)
[array (
  0 =&gt; 'XXXX',
  1 =&gt; 'XXXX',
  2 =&gt; XXXX.jpg',
  3 =&gt; 0,
)]
Error code: dmlwriteexception !!
!! Stack trace: * line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 291 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database-&gt;query_end()
* line 1357 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database-&gt;query_end()
* line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database-&gt;insert_record_raw()
* line 72 of /course/format/grid/db/upgrade.php: call to mysqli_native_moodle_database-&gt;insert_record()
* line 709 of /lib/upgradelib.php: call to xmldb_format_grid_upgrade()
* line 1935 of /lib/upgradelib.php: call to upgrade_plugins()
* line 202 of /admin/cli/upgrade.php: call to upgrade_noncore()
 !!
```

It would be great if you could fix this issue.

Best regards
Andreas

**Comment by gjb2048** [comment] 2022-09-05 18:05
Duplicate of https://github.com/gjb2048/moodle-format_grid/issues/164 and I have no idea why this is happening or can replicate!  Please see and try a new version of the upgrade script -> https://moodle.org/mod/forum/discuss.php?d=437697#p1762580.  Is this a test server?  If so, did the 'format_grid_image' table exist before the script was run?  Was the site in Maintenance mode?  Were any courses being accessed?  Does your PHP install use multiple processes?

**Comment by gjb2048** [comment] 2022-09-05 18:14
Could I have a CSV export of the format_grid_icon and format_grid_image tables from your test server where the error happens please Andreas? i.e. where the data is not sensitive.

**Comment by gjb2048** [comment] 2022-09-05 18:57
@abkoch Does the issue occur if you update via the UI?

**Comment by gjb2048** [comment] 2022-09-05 19:31
Ok, did an update from M3.9 to M4.0 and used the CLI (on Windows with MINGW64) and still cannot replicate.

**Comment by abkoch** [comment] 2022-09-05 19:35
Thank you very much for your help.The problem occurs via CLI and via UI, too. I try to create a dump of the tables without private data.

**Comment by abkoch** [comment] 2022-09-05 20:08
All data causing this issue seems to have one similarity: there's an underscore in its attribute "image" of "mdl_format_grid_image". Coincidence or not?

**Comment by gjb2048** [comment] 2022-09-05 20:40
Ok, why would an underscore in the image attribute cause a unique key failure in the sectionid attribute?

**Comment by gjb2048** [comment] 2022-09-05 20:49
And what evidence?  All the data I have has the breakage on the first image listed.

**Comment by gjb2048** [comment] 2022-09-05 21:56
Ok, underscores are a 'Wild goose chase', repeated the whole upgrade procedure and cannot replicate!

![Screenshot 2022-09-05 224245](https://user-images.githubusercontent.com/1058419/188515484-72d9fe9b-8556-4aa3-a488-140205463dc7.png)

**Comment by gjb2048** [comment] 2022-09-05 21:59
@abkoch What database engine are you using please?

**Comment by gjb2048** [comment] 2022-09-05 22:24
And @abkoch, what OS with version are you running please?

**Comment by abkoch** [comment] 2022-09-06 11:15
First of all, sorry for my misleading hint.

OS: CentOS 7.9
MySQL: MariaDB 10.2.33
Update process: maintenance mode switched on, removed old "grid"-folder, copied new "grid"-folder, started upgrade via CLI (2nd try via UI failed, too)

Is there a possibility to send you sample table data via private message or mail?

**Comment by gjb2048** [comment] 2022-09-06 12:03
@abkoch Thanks, I'm running a Windows install but with MySQL 8.0.30, so wondering if it could be a Maria DB thing?

**Comment by gjb2048** [comment] 2022-09-06 12:04
@abkoch Oh, please use the contact details in Support.md file.

**Comment by gjb2048** [comment] 2022-09-06 15:51
@abkoch Ok, I've fixed a secondary issue (in #164) that when fails, and then Moodle can then want to run the script again will then cause the issue.  Thus, please patch with https://raw.githubusercontent.com/gjb2048/moodle-format_grid/185631a455119a4e4fd23852194e715e6782dd1d/db/upgrade.php - but do start on a clean test install or delete the format_grid_image table and the entries in the files table 'format_grid/sectionimage' that they refer to.

**Comment by gjb2048** [comment] 2022-09-08 10:42
@abkoch Please could you test and confirm, as I'd like to make a stable release soon.

**Comment by abkoch** [comment] 2022-09-08 14:55
You wrote
> delete the format_grid_image table
And that's true on a productive environment that already uses format_grid. Otherwise the upgrade fails with "table format_grid_image" already exists.

**Comment by gjb2048** [comment] 2022-09-08 15:13
Where have I written code that deletes the format_grid_image table in the upgrade script?

**Comment by gjb2048** [comment] 2022-09-08 15:19
@abkoch That was only so that you could retest the updated code from the situation that the previous code put you in that now won't happen.

**Closed** 2022-09-08 19:51 UTC
Labels: Information required, Cannot reproduce
