### ISSUE TITLE
Log entries?

### ISSUE THREAD

**Issue by checta** [gjb2048/moodle-format_grid#75] opened 2018-08-17 09:49 UTC
Hi Gareth,
I really love this format, thank you for all your work on it. 

I have an issue regarding logging, and would like some clarification on what to expect or how to resolve this please.

When loading a course with this format, without accessing any activities the activities are logged in the moodle log as being viewed. When clicking on one of the grid sections and moving through to the subsequent sections nothing is logged. So the log isn't showing what activities the user is actually accessing in the course. Should there be entries in the log when a course section is accessed from the grid?

Thanks,
Claire
<img width="250" alt="example h5p embedded activity" src="https://user-images.githubusercontent.com/42466233/44260021-9249d700-a256-11e8-8032-6abebee068ff.png">
<img width="250" alt="example course setup - grid format" src="https://user-images.githubusercontent.com/42466233/44260022-9249d700-a256-11e8-85dc-0b939541352f.png">
<img width="917" alt="screen shot 2018-08-17 at 3 42 46 pm" src="https://user-images.githubusercontent.com/42466233/44260023-9249d700-a256-11e8-93b7-85901c114a70.png">

**Comment by gjb2048** [comment] 2018-08-17 15:55
Hi Claire,

No idea.  The grid format does no logging but calls the course renderer as per every other course format in relation to course modules.

Gareth

**Comment by gjb2048** [comment] 2018-08-17 15:56
What version of the format and Moodle please?

**Comment by checta** [comment] 2018-08-17 22:42
Thanks Gareth,
I'm using Moodle 3.4 and Grid format 3.4.0.3
Cheers,
Claire

**Comment by gjb2048** [comment] 2019-04-02 15:49
Hi Claire,

Is this still an issue please?

Gareth

**Comment by gjb2048** [comment] 2019-04-02 16:24
Ok, cannot reproduce in M3.6.

**Comment by gjb2048** [comment] 2019-11-16 13:07
Still an issue, if no reply then will close.

**Comment by checta** [comment] 2019-11-17 00:05
Hi Gareth,
Yes still a problem

Thanks,
Claire

Claire Young
+61 406 754 668

**Comment by gjb2048** [comment] 2019-11-17 11:46
Dear Claire,

I've checked again and whilst the section navigation is not being logged as it is with the topics format on 'one section per page', the course and module view events are.  Therefore there is nothing to fix in terms of the original issue you posted.  Viewing the activities / resources (modules) is being logged.  Please check your system on other course formats to see if it is a local configuration issue or one whereby certain courses are not logged.

Therefore still 'cannot reproduce'.

G

**Comment by gjb2048** [comment] 2022-09-29 10:57
@checta Closing as no reply after several years.

**Closed by gjb2048** 2022-09-29 10:57 UTC
Labels: Cannot reproduce
